import { type NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  if (session) {
    return (
      <div className="flex h-[calc(100vh-56px)] justify-center bg-grey">
        <main>
          Signed in as {session.user.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
        </main>
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>dev.to</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="relative">
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </div>
      </div>
    </>
  );
};

export default Home;
